// import type { Metadata } from "next";
// import { My_Soul, Archivo } from "next/font/google";
// import "@fortawesome/fontawesome-svg-core/styles.css";
// import { config } from "@fortawesome/fontawesome-svg-core";
// config.autoAddCss = false;
// import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
// import { faAt } from "@fortawesome/free-solid-svg-icons";
// import "./globals.css";
// import Link from "next/link";

// const mySoul = My_Soul({ subsets: ["latin"], weight: ["400"] });
// const archivo = Archivo({ subsets: ["latin"], weight: ["400", "700"] });

// export const metadata: Metadata = {
//   title: { default: "The New York Tymes", template: "%s | The New York Tymes" },
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* ${archivo.className} */}
      <body className={` px-[20vw] py-12 lg:px-[10vw]`}>
        {/* <nav className="mb-4 text-center">
          <Link href="/">
            <h1 className={`${mySoul.className} text-5xl`}>
              The New York Tymes
            </h1>
          </Link>
          <p className="text-xl">the most original publisher in town</p>
        </nav> */}
        {children}
        {/* <footer className="flex justify-center mt-4">
          <div>
            <FontAwesomeIcon icon={faAt} className="mr-1" />
            2023 The New York Tymes Company
          </div>
        </footer> */}
      </body>
    </html>
  );
}
