import type { Metadata } from "next";
import { My_Soul, Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const mySoul = My_Soul({ subsets: ["latin"], weight: ["400"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: { default: "The New York Tymes", template: "%s | The New York Tymes" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="px-[20vw] lg:px-[10vw]">
          <div className="py-6 text-center">
            <Link href="/">
              <h1 className={`${mySoul.className} text-4xl`}>
                The New York Tymes
              </h1>
            </Link>
            <p className="text-lg">the most original publisher in town</p>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
